const DamageReport = require("../../models/disasterModel/DamageReportModel");
const Disaster = require("../../models/disasterModel/DisasterModel");

const buildApprovedSummaryDescription = (approvedReports = []) => {
  if (!approvedReports.length) {
    return "No admin-approved user damage reports yet.";
  }

  const byType = approvedReports.reduce((acc, report) => {
    const key = report.damageType || "Other";
    acc[key] = (acc[key] || 0) + 1;
    return acc;
  }, {});

  const breakdown = Object.entries(byType)
    .map(([type, count]) => `${type}: ${count}`)
    .join(", ");

  const detailSnippets = approvedReports
    .map((report) => (report.damageDescription || "").trim())
    .filter(Boolean)
    .slice(0, 3)
    .map((text) => (text.length > 90 ? `${text.slice(0, 90)}...` : text));

  const detailSummary = detailSnippets.length
    ? ` Key observations: ${detailSnippets.join(" | ")}.`
    : "";

  return `Summary generated from ${approvedReports.length} admin-approved user reports. Type breakdown: ${breakdown}.${detailSummary}`;
};

const findOrCreateAutoSummaryReport = async (disasterId, disaster) => {
  let autoSummaryReport = await DamageReport.findOne({
    disasterId,
    $or: [{ isAutoGenerated: true }, { reporterName: "System Auto Generated" }],
  });

  if (!autoSummaryReport) {
    autoSummaryReport = await DamageReport.create({
      disasterId,
      reporterName: "System Auto Generated",
      contactNumber: "N/A",
      damageType: "Other",
      damageDescription: "No admin-approved user damage reports yet.",
      location: disaster.location,
      images: [],
      verificationStatus: "Approved",
      estimatedLoss: 0,
      isAutoGenerated: true,
    });
  }

  return autoSummaryReport;
};

const recalculateAutoGeneratedSummary = async (disasterId) => {
  const [disaster, approvedReports] = await Promise.all([
    Disaster.findById(disasterId),
    DamageReport.find({
      disasterId,
      reporterName: { $ne: "System Auto Generated" },
      verificationStatus: { $in: ["Approved", "Verified"] },
    }),
  ]);

  if (!disaster) {
    throw new Error("Disaster not found");
  }

  const autoSummaryReport = await findOrCreateAutoSummaryReport(disasterId, disaster);

  const numericLossValues = approvedReports
    .map((report) => Number(report.estimatedLoss))
    .filter((value) => Number.isFinite(value));

  const totalEstimatedLoss = numericLossValues.reduce((sum, value) => sum + value, 0);

  const aggregatedImages = [
    ...new Set(
      approvedReports.flatMap((report) =>
        Array.isArray(report.images) ? report.images : []
      )
    ),
  ];

  autoSummaryReport.damageType = "Other";
  autoSummaryReport.damageDescription = buildApprovedSummaryDescription(approvedReports);
  autoSummaryReport.estimatedLoss = totalEstimatedLoss;
  autoSummaryReport.images = aggregatedImages;
  autoSummaryReport.verificationStatus = "Approved";
  autoSummaryReport.reporterName = "System Auto Generated";
  autoSummaryReport.contactNumber = "N/A";
  autoSummaryReport.isAutoGenerated = true;
  autoSummaryReport.location = disaster.location || autoSummaryReport.location;

  return await autoSummaryReport.save();
};

const createDamageReport = async (data) => {
  if (!data.damageDescription) {
    throw new Error("Damage description is required");
  }

  const disaster = await Disaster.findById(data.disasterId);
  if (!disaster) {
    throw new Error("Disaster not found");
  }

  if (disaster.verificationStatus !== "Verified") {
    throw new Error("Damage reports can only be submitted after admin verifies the disaster");
  }

  data.isAutoGenerated = false;
  data.verificationStatus = "Pending";

  const report = await DamageReport.create(data);
  return report;
};

const getReportsByDisaster = async (disasterId) => {
  await recalculateAutoGeneratedSummary(disasterId);
  return await DamageReport.find({ disasterId })
    .sort({ createdAt: -1 })
    .populate("disasterId");
};

const getReportById = async (reportId) => {
  const report = await DamageReport.findById(reportId).populate("disasterId");
  if (!report) {
    throw new Error("Report not found");
  }

  return report;
};

const verifyReport = async (reportId, status) => {
  const normalizedStatus = status === "Verified" ? "Approved" : status;
  const allowedStatuses = ["Approved", "Rejected", "Pending"];
  if (!allowedStatuses.includes(normalizedStatus)) {
    throw new Error("Invalid verification status");
  }

  const report = await DamageReport.findById(reportId);

  if (!report) {
    throw new Error("Report not found");
  }

  if (report.isAutoGenerated) {
    throw new Error("Auto-generated summary report cannot be manually approved or rejected");
  }

  report.verificationStatus = normalizedStatus;
  const updatedReport = await report.save();

  await recalculateAutoGeneratedSummary(report.disasterId);

  return updatedReport;
};

module.exports = {
  createDamageReport,
  getReportsByDisaster,
  getReportById,
  verifyReport,
  recalculateAutoGeneratedSummary,
};
